#ifndef CLASSIFIER_H
#define CLASSIFIER_H

/*
 * Auto-generated by train.py — do not edit manually.
 * Classes (index → name):
 *   0: horizontal_shake
 *   1: rest
 *   2: vertical_shake
 */

#include <float.h>

#include <string.h>
void score(double * input, double * output) {
    double var0[3];
    if (input[18] <= 1073.0) {
        memcpy(var0, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[25] <= 25.725298166275024) {
            if (input[19] <= 1438844.1875) {
                memcpy(var0, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[7] <= 698.8768310546875) {
                    memcpy(var0, (double[]){0.043478260869565216, 0.0, 0.9565217391304348}, 3 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.6666666666666666, 0.0, 0.3333333333333333}, 3 * sizeof(double));
                }
            }
        } else {
            memcpy(var0, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    }
    memcpy(output, var0, 3 * sizeof(double));
}


/* Returns the index of the predicted class (use GESTURE_NAMES to get the label). */
static inline int predict(float *input) {
    double scores[3];
    double dinput[26];
    for (int i = 0; i < 26; i++) dinput[i] = (double)input[i];
    score(dinput, scores);
    int best = 0;
    for (int i = 1; i < 3; i++)
        if (scores[i] > scores[best]) best = i;
    return best;
}

static const char *GESTURE_NAMES[] = {
    "horizontal_shake",
    "rest",
    "vertical_shake",
};

#endif /* CLASSIFIER_H */
