#!/usr/bin/env python3
"""
Decision Tree Training (Direction-Invariant)
Usage: python train_invariant.py

Reads ../Training_Data/train_invariant.csv and ../Training_Data/val_invariant.csv,
trains a DecisionTreeClassifier, prints evaluation metrics,
and writes ../Training_Data/classifier_invariant.h (C code for STM32).

Dependencies: scikit-learn, m2cgen
  pip install scikit-learn m2cgen
"""

import os
import csv
import m2cgen as m2c
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import classification_report, confusion_matrix

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(os.path.dirname(SCRIPT_DIR), "Training_Data")
TRAIN_FILE = os.path.join(DATA_DIR, "train_invariant.csv")
VAL_FILE   = os.path.join(DATA_DIR, "val_invariant.csv")
C_OUT_FILE = os.path.join(DATA_DIR, "classifier_invariant.h")

MAX_DEPTH  = 4
SEED       = 42


def load_csv(path):
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = [c for c in reader.fieldnames if c != "label"]
        X, y = [], []
        for row in reader:
            X.append([float(row[col]) for col in fieldnames])
            y.append(row["label"])
    return X, y, fieldnames


def main():
    for path in (TRAIN_FILE, VAL_FILE):
        if not os.path.isfile(path):
            print(f"[ERROR] Not found: {path}")
            print("        Run feature_extractor_invariant.py then split_invariant.py first.")
            raise SystemExit(1)

    X_train, y_train, feature_names = load_csv(TRAIN_FILE)
    X_val,   y_val,   _             = load_csv(VAL_FILE)

    print(f"Train: {len(X_train)} samples   Val: {len(X_val)} samples")
    print(f"Features: {len(feature_names)}\n")

    clf = DecisionTreeClassifier(max_depth=MAX_DEPTH, random_state=SEED)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_val)
    print("=== Validation results ===")
    print(classification_report(y_val, y_pred, digits=3))

    classes = clf.classes_
    print("Confusion matrix (rows=actual, cols=predicted):")
    print(f"  Classes: {list(classes)}")
    cm = confusion_matrix(y_val, y_pred, labels=classes)
    for label, row in zip(classes, cm):
        print(f"  {label:20s}: {list(row)}")

    print("\n=== Tree structure ===")
    print(export_text(clf, feature_names=feature_names))

    c_code = m2c.export_to_c(clf).replace(
        "void score(double * input, double * output)",
        "static void score(double * input, double * output)", 1
    )

    class_lines = "\n".join(
        f'    "{name}",' for name in classes
    )
    header = f"""\
#ifndef CLASSIFIER_INVARIANT_H
#define CLASSIFIER_INVARIANT_H

/*
 * Auto-generated by train_invariant.py — do not edit manually.
 * Direction-invariant model: works regardless of board heading.
 *
 * Classes (index → name):
{chr(10).join(f" *   {i}: {name}" for i, name in enumerate(classes))}
 */

#include <float.h>

{c_code}

/* Returns the index of the predicted class. */
static inline int predict_invariant(float *input) {{
    double scores[{len(classes)}];
    double dinput[{len(feature_names)}];
    for (int i = 0; i < {len(feature_names)}; i++) dinput[i] = (double)input[i];
    score(dinput, scores);
    int best = 0;
    for (int i = 1; i < {len(classes)}; i++)
        if (scores[i] > scores[best]) best = i;
    return best;
}}

static const char *GESTURE_NAMES_INV[] = {{
{class_lines}
}};

#endif /* CLASSIFIER_INVARIANT_H */
"""

    with open(C_OUT_FILE, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"[SAVED]  {C_OUT_FILE}")
    print("\nInclude classifier_invariant.h in your STM32 project and call:")
    print("  float features[{n}] = {{ ... }};".format(n=len(feature_names)))
    print("  int gesture = predict_invariant(features);")
    print("  // GESTURE_NAMES_INV[gesture] -> label string")


if __name__ == "__main__":
    main()
