#ifndef CLASSIFIER_INVARIANT_H
#define CLASSIFIER_INVARIANT_H

/*
 * Auto-generated by train_invariant.py — do not edit manually.
 * Direction-invariant model: works regardless of board heading.
 *
 * Classes (index → name):
 *   0: horizontal_shake
 *   1: rest
 *   2: vertical_shake
 */

#include <float.h>

#include <string.h>
void score(double * input, double * output) {
    double var0[3];
    if (input[4] <= 766.0910797119141) {
        memcpy(var0, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    } else {
        if (input[5] <= 23020.5) {
            memcpy(var0, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        } else {
            memcpy(var0, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
        }
    }
    memcpy(output, var0, 3 * sizeof(double));
}


/* Returns the index of the predicted class. */
static inline int predict_invariant(float *input) {
    double scores[3];
    double dinput[18];
    for (int i = 0; i < 18; i++) dinput[i] = (double)input[i];
    score(dinput, scores);
    int best = 0;
    for (int i = 1; i < 3; i++)
        if (scores[i] > scores[best]) best = i;
    return best;
}

static const char *GESTURE_NAMES_INV[] = {
    "horizontal_shake",
    "rest",
    "vertical_shake",
};

#endif /* CLASSIFIER_INVARIANT_H */
